# Configuration for NoDupePlugin

# List of high-vulnerability items (by Material name)
# Example: SHULKER_BOX, BLACK_SHULKER_BOX, etc.
high-vulnerability-items:
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - LIME_SHULKER_BOX
  - PINK_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - RED_SHULKER_BOX
  - BLACK_SHULKER_BOX
  - MOB_SPAWNER

# Enable or disable debug logging
debug: false

# Notify the offending player when duplicates are detected
notify-player: false

# Automatically remove duplicated items when detected
remove-duplicates: true

# Enable or disable the /simdupe command. Should only be enabled for testing!
enable-simdupe: false

# Automatically remove blacklisted items
remove-blacklisted-items: true

# List of blacklisted items that should be automatically removed from player inventories
blacklisted-items:
  - BEDROCK
  - COMMAND_BLOCK
  - COMMAND_BLOCK_MINECART
  - STRUCTURE_BLOCK
  - BARRIER

blacklisted-metadata:
  SPAWNER:
    - "ender dragon spawner"

banned-spawner-entities:
  - ENDER_DRAGON
